name: Build and deploy Python project to Azure Function App - cvthequematching

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # la racine
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Tu peux ajouter une étape pour exécuter les tests ici
        -name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*" ".git/*"

        -name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
  with:
       -name: python-app
       path: release.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
     - name: Download artifact from build job
  uses: actions/download-artifact@v4
  with:
    name: python-app
     
  -name: Deploy to Azure Functions
  uses: Azure/functions-action@v1
  id: deploy-to-function
  with:
    app-name: 'cvthequematching'
    slot-name: 'Production'
    package: release.zip
    publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_102F607541004774BB4B24263EE7C7CF }}
    sku: 'flexconsumption'
